name: HTML Website CI

on:
  push:
    branches:
      - main

jobs:

  website-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display repository files
        run: ls -la

      - name: Check index.html
        run: test -f index.html

      - name: Check CSS
        run: test -f style.css

      - name: Website validation passed
        run: echo "Website validation PASSED"